### ISSUE TITLE
Coordinates have a slight offset

### ISSUE THREAD

**Issue by ghostdogpr** [southkorea/seoul-maps#2]
If you compare the coordinates from this repo with another map service such as Google Maps or OpenStreetMap, you can see that they do not exactly match. They are slightly shifted to the south east.

It can be seen easily here: https://github.com/southkorea/seoul-maps/blob/master/kostat/2013/json/seoul_submunicipalities_topo.json
Zoom a little bit and look at the borders of Seoul in OpenStreetMap.

When loading the source shapefile in QGIS, we can see the offset is already there.

**Comment by devdoomari** [comment]
is it because of map projection difference? 
I heard WGS84 on GoogleMaps and some korean maps use difference coord systems.

**Comment by ghostdogpr** [comment]
The source shapefile uses a totally different projection indeed, but it is well recognized by QGIS, except for this little offset. I am starting to wonder if the source shapefile isn't simply wrong...
